### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by pascalandy** [juan-g/WorldCasper2#20]
As there is no release on this repo, I'm wondering, do you consider this project stable?

I'll be glad to test the French version :)

**Comment by pascalandy** [comment]
Good! I'll test it :)

**Comment by miko007** [comment]
why is this functionality not simply merged into upstream casper?

**Comment by pascalandy** [comment]
It looks this project is not merging the updates made in the original project:
https://github.com/TryGhost/Casper/commits/master

I would like to rely on this project but I need to know if it's following the parent updates. 
Thanks!

**Comment by juan-g** [comment]
@miko007 I also hope Casper itself will be translatable in the future. That time, WorldCasper2 will cease to be needed, of course. For the time being, the Ghost team asked me to maintain WorldCasper1 and WorldCasper2 as translatable clones of Casper 1.4 and 2.x.

@pascalandy Sorry for the recent delay in updates/releases. Today's WorldCasper2 v2.4.2 release is based on the current Casper 2.4.2, made translatable. The original Casper commits appear now on the second page of recent WorldCasper2 commits, due to the git rebase that moves all i18n commits on top of the Casper ones, with a new date, when updating the Casper base.

**Comment by pascalandy** [comment]
Good to know. I appreciate your devotion 🙌. Don't hesitate to buzz me for help or to ask to to test stuff.

> I also hope Casper itself will be translatable in the future. That time, WorldCasper2 will cease to be needed, of course. For the time being, the Ghost team asked me to maintain WorldCasper1 and WorldCasper2 as translatable clones of Casper 1.4 and 2.x.
